### ISSUE TITLE
How to build Protein-chain-pairs dataset

### ISSUE THREAD

**Issue by htma** [valentynbez/tmvec#2]
Hi, 

If I want   to re-train your tm-vec model, how to build the  Protein-chain-pairs dataset firstly?

Would you provide he source code about this part, or give me some more details.

Thanks
![Uploading 1733360644546.png…]()

**Comment by valentynbez** [comment]
Hello @htma, 
Please, refer to the original paper for details: https://www.nature.com/articles/s41587-023-01917-2
The data is on Zenondo sever: https://zenodo.org/records/8038377

**Comment by htma** [comment]
@valentynbez #2 
Thanks for your reply, 

In your original paper (https://www.nature.com/articles/s41587-023-01917-2), "**Protein-chain-pairs dataset**." section, you said the number of protein chains up to 300 residules long was 277,000 chains. 
But the number of your final train pairs "swiss_under_300_141M.csv" was 141,331,170 (141M), 
**my question is how you filtered 277,000*277,000 pairs into final 141M pairs?**

**Comment by valentynbez** [comment]
Please, contact original authors of the paper for clarification. Thank you!

**Comment by htma** [comment]
Got it. Thanks!
